### PR TITLE
updated referenceid

### PR DESCRIPTION
**Pull request by OttoVT**

### CODE REVIEW

**Comment by OttoVT** [comment]
Approve if you can but do not merge

**Review by KonstantinRyazantsev — COMMENTED** [review]
It would be good to show both account reference ID and withdrawal reference ID on the withdrawal details window:

image

**Comment by OttoVT** [comment]
Let's put it in another task. First, I should close it with validation in https://swisschain.atlassian.net/browse/SIR-1349

**Review by KonstantinRyazantsev — COMMENTED** [review]
Check this https://github.com/swisschain/Sirius.Api/pull/88#discussion_r495746220

**Comment by OttoVT** [comment]
it was already accountReferenceId

**Pull request merged**
